GET http://localhost:8080/password/generate

###

POST http://localhost:8080/password/validate
Content-Type: application/json

{
    "password": "passwdGen0nrdsoabybncq"
}

###

POST http://localhost:8080/secure/breached
Content-Type: application/json

{
    "password": "123456789"
}
